### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/cli/CommandLineParser

### ISSUE THREAD

**Issue by sharp** [nuxeo-archives/jodconverter.bak#3]
```
java -jar target/jodconverter-core-3.0-NX7-SNAPSHOT.jar a.doc a.pdf
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/cli/CommandLineParser
    at java.lang.Class.getDeclaredMethods0(Native Method)
    at java.lang.Class.privateGetDeclaredMethods(Class.java:2442)
    at java.lang.Class.getMethod0(Class.java:2685)
    at java.lang.Class.getMethod(Class.java:1620)
    at sun.launcher.LauncherHelper.getMainMethod(LauncherHelper.java:494)
    at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:486)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.cli.CommandLineParser
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
    ... 6 more

```

**Comment by jcarsique** [comment]
This is not an issue: the produced artifact is not an "all-in-one" (aka "shaded") JAR, it is not embedding its own dependencies. When using that JAR, you must provided it the right classpath.
If you're interested in additionally producing such a JAR, please contribute changes to make use of [maven-shade-plugin](http://maven.apache.org/plugins/maven-shade-plugin/).
